using System.Collections.Generic;
using ReactUnity.Scripting;
using UnityEngine;

namespace ReactUnity.Tests
{
    public class CodeTransformer
    {
        private static CodeTransformer instance;
        public static CodeTransformer Instance => instance = instance ?? new CodeTransformer();

        public IJavaScriptEngine Engine;
        private IJavaScriptEngineFactory EngineFactory;

        public bool Initialized { get; private set; } = false;

        public CodeTransformer(JavascriptEngineType type = JavascriptEngineType.Auto)
        {
            EngineFactory = JavascriptEngineHelpers.GetEngineFactory(type);
            Engine = EngineFactory.Create(null, false, false, (res) => {
                // Generated by scripts/test-transformer/build.mts - `pnpm build:test-transformer`.
                res.Execute(Resources.Load<TextAsset>("ReactUnity/tests/scripts/sucrase-standalone").text, "ReactUnity/sucrase-standalone");
                Initialized = true;
            });
        }

        public static IEnumerator<string> TransformCode(string code)
        {
            return Instance.Transform(code);
        }

        /// <summary>Turns a fixture's JSX snippet into something an engine can execute.</summary>
        ///
        /// Sucrase rather than Babel, and not for speed: this runs *inside* the engine, on
        /// Unity's main thread inside a coroutine, so its call depth is charged to a C stack
        /// that is already deep. Babel did not fit on the 6000.5 line - every ButtonTests and
        /// InputTests case died in setup with an uncatchable StackOverflowException. Pruning
        /// its presets did nothing, because the depth is Babel's parse-then-traverse floor and
        /// not the plugins on top of it. Sucrase rewrites a token stream instead, and fits.
        ///
        /// `disableESTransforms` is correctness, not tuning. Lowering optional chaining routes
        /// the call through a helper that does `value.call(...)`, and a C# method handle is not
        /// a JS function under ClearScript, so `Globals.list?.Add(x)` threw. All three engines
        /// run the modern syntax natively; leaving it alone is both shallower and correct.
        private string TransformNow(string code)
        {
            Engine.SetGlobal("_codeToTransform", new { code });
            return Engine.Evaluate("Sucrase.transform(_codeToTransform.code, { transforms: ['jsx', 'imports'], disableESTransforms: true, production: true, filePath: 'test.jsx' }).code")?.ToString();
        }

        public IEnumerator<string> Transform(string code)
        {
            while (!Initialized) yield return null;
            yield return TransformNow(code);
        }
    }
}
