/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py

namespace Facebook.Yoga
{
    public enum YogaPositionType
    {
        Default = 1,
        Static = 0,
        Relative = 1,
        Absolute = 2,
    }
}
